package org.brandon.utilidades;

public class Ayuda{
	public void ayudaadmin(){
		System.out.println("Comandos que puede usar el Administrador");
		System.out.println("");
		System.out.println("list products - Muestra un listado de los productos");
		System.out.println("SINTAXIS: list products");
		System.out.println("");
		System.out.println("show product - Muestra informacion detallada de un producto. ");
		System.out.println("SINTAXIS: show product[nombre del producto]");
		System.out.println("");
		System.out.println("list downlines - Muestra una lista de tus downlines o del downline especificado");
		System.out.println("SINTAXIS: list downlines [idDownline]");
		System.out.println("");
		System.out.println("show downline - Muestra informacion detallada del downline especificado, si se agrega [money] mostrara solo la informacion de volumen monetario");
		System.out.println("SINTAXIS: show downline [idDownline] [Money]");
		System.out.println("");
		System.out.println("show history - Muestra el historial de downlines agregados, si se agrega buy mostrara el historial de compras de mi perfil, si se agrega downline y el id del  downline se mostrara o bien el historial de downlines agregados o de compras dependiendo de la combinacon (si se le agrega buy o no)");
		System.out.println("SINTAXIS: show history [buy] [downline] [idDownline] ");
		System.out.println("");
		System.out.println("show me - Muestra la informacion de mi perfil, si se coloca money mostrara solo la informacion de volumen monetario");
		System.out.println("SINTAXIS: show me [money]");
		System.out.println("");
		System.out.println("logout - Este comando sirve para cerrar sesion");
		System.out.println("SINTAXIS: logout ");
		System.out.println("");
		System.out.println("search downline - Muestra la información detallada del downline si coincide con la busqueda");
		System.out.println("SINTAXIS: search downline [Datos]");
		System.out.println("");
		System.out.println("exit - Sale totalmente del programa");
		System.out.println("SINTAXIS: exit");
		System.out.println("");
		System.out.println("add product - Agrega un producto del stock");
		System.out.println("SINTAXIS: add product nombre=[nombre del nuevo producto] categoria=[categoria del nuevo producto]  precio=[precio del nuevo producto]");
		System.out.println("");
		System.out.println("remove product - Elimina un producto del stock");
		System.out.println("SINTAXIS: remove product nombre=[nombre del nuevo producto] categoria=[categoria del nuevo producto]  precio=[precio del nuevo producto]");
		System.out.println("");
		System.out.println("edit product - Modifica un producto del stock");
		System.out.println("SINTAXIS: edit product nombre=[nombre del nuevo producto] categoria=[categoria del nuevo producto]  precio=[precio del nuevo producto]");
		System.out.println("");
		System.out.println("show sales - Muestra informacion de venta de un producto si se especifica, o de todos si no se especifica.");
		System.out.println("SINTAXIS: show sales [product [nombre del producto] ]");
		System.out.println("");
		System.out.println("add user - Agrega un Administrador");
		System.out.println("SINTAXIS: add user nombre=[nombre que desea ponerle al admnistrador] password=[contrasenha del administrador] nick=[nombre de usuario del nuevo administrador]");
		System.out.println("");
	}
	public void ayudamiembro(){
		System.out.println("Comandos que puede usar el Miembro");
		System.out.println("");
		System.out.println("list products - Muestra un listado de los productos");
		System.out.println("SINTAXIS: list products");
		System.out.println("");
		System.out.println("show product - Muestra informacion detallada de un producto. ");
		System.out.println("SINTAXIS: show product[nombre del producto]");
		System.out.println("");
		System.out.println("list downlines - Muestra una lista de tus downlines o del downline especificado");
		System.out.println("SINTAXIS: list downlines [idDownline]");
		System.out.println("");
		System.out.println("show downline - Muestra informacion detallada del downline especificado, si se agrega [money] mostrara solo la informacion de volumen monetario");
		System.out.println("SINTAXIS: show downline [idDownline] [Money]");
		System.out.println("");
		System.out.println("show history - Muestra el historial de downlines agregados, si se agrega buy mostrara el historial de compras de mi perfil, si se agrega downline y el id del  downline se mostrara o bien el historial de downlines agregados o de compras dependiendo de la combinacion. (si se le agrega buy o no)");
		System.out.println("SINTAXIS: show history [buy] [downline] [idDownline] ");
		System.out.println("");
		System.out.println("show me - Muestra la informacion de mi perfil, si se coloca money mostrara solo la informacion de volumen monetario");
		System.out.println("SINTAXIS: show me [money]");
		System.out.println("");
		System.out.println("logout - Este comando sirve para cerrar sesion");
		System.out.println("SINTAXIS: logout ");
		System.out.println("");
		System.out.println("edit me - Este comando modifica datos del usuario");
		System.out.println("SINTAXIS: edit me [Parametro]=[Nuevo Valor]");
		System.out.println("");
		System.out.println("add downline - Agregar un downline a tu perfil, o a downline especificado");
		System.out.println("SINTAXIS: add downline [Datos] [down] [idDownline] [Producto]");
		System.out.println("");
		System.out.println("search downline - Muestra la información detallada del downline si coincide con la busqueda");
		System.out.println("SINTAXIS: search downline [Datos]");
		System.out.println("");
		System.out.println("buy product - Comprar un producto del Stock");
		System.out.println("SINTAXIS: buy product [Nombre del Producto] [Numero de Tarjeta]");
		System.out.println("");
		System.out.println("exit - Sale totalmente del programa");
		System.out.println("SINTAXIS: exit");
		System.out.println("");
	}
}